/**
 * Created by Sanchez on 02.10.2022.
 */

public with sharing class KidsGroupService {
    public static void validateAmountKidsByGroup(List<Kids_Group__c> groups) {
        /*try {
            for (Kids_Group__c g : groups) {
                if (g.Kid_Group_Amount__c > g.Limit_Kids_by_Group__c) {
                    g.addError('Group is FULL! Create new Group !');
                }
            }
        }catch (Exception e){
            throw e;
        }*/
    }
}