/**
 * Created by Sanchez on 02.10.2022.
 */

public with sharing class KidsGroupService {
    /*public static void validateKidAgeByGroup(List<Contact> kids) {
        *//*for (Contact k : kids) {
            if (k.Age__c < 6 || k.Age__c == null) {
                k.addError('Student is too young!');
            }
        }*//*
    }*/

    /*public static void updateAmountOfKidsOnGroup(List<Contact> kids) {
        update new Kids_Group__c(Id = groupId, Kid_Group_Amount__c = relativeContactList.size());
    }*/

}